import "dart:convert";
import "dart:io";

import "package:flutter_test/flutter_test.dart";
import "package:path/path.dart" as path;

void main() {
  const fixturePath =
      "fixtures/compat/native-install-helper/v1/journal-transitions.json";
  const generatorPath = "tool/generate_native_install_helper_fixtures.dart";

  test("pure recovery model and fixture tests exist", () {
    for (final requiredPath in <String>[
      "native_runtime/cpp/install_helper_contract.h",
      "native_runtime/cpp/install_helper_contract.cc",
      "native_runtime/cpp/install_helper_contract_fixture_tests.cc",
    ]) {
      expect(
        File(requiredPath).existsSync(),
        isTrue,
        reason: "$requiredPath must exist",
      );
    }
  });

  test("generated crash matrix covers every required adversarial class",
      () async {
    final fixture = await _readJson(fixturePath);
    final cases = _mapList(fixture, "recoveryCases");
    final names = cases.map((entry) => entry["name"]).toSet();
    expect(
      names,
      containsAll(<String>{
        "swap death before prepared journal durable",
        "swap death after prepared durable",
        "swap death before backupCreated durable",
        "swap death after backupCreated durable",
        "swap death before targetActivated durable",
        "swap death after targetActivated durable",
        "swap death before completed durable",
        "swap death after completed durable",
        "manager death before prepared journal durable",
        "manager death after prepared durable",
        "manager death before managerStarted durable",
        "manager death after managerStarted durable",
        "manager death before verificationPending durable",
        "manager death after verificationPending durable",
        "manager death before completed durable",
        "manager death after completed durable",
        "repeated recovery after rollback",
        "repeated recovery after completion",
        "live owner recovery rejection",
        "torn journal write",
        "short journal write",
        "disk full before journal replacement",
        "directory flush failure",
        "corrupt journal",
        "unknown journal version",
        "injected prepared sibling name",
        "owner generation mismatch",
        "ambiguous target and backup state",
      }),
    );
  });

  test("every crash case converges to one closed outcome", () async {
    final fixture = await _readJson(fixturePath);
    const outcomes = <String>{
      "verifiedOldTarget",
      "verifiedNewTarget",
      "manualActionRequired",
    };
    for (final entry in _mapList(fixture, "recoveryCases")) {
      final expected = Map<String, dynamic>.from(entry["expected"] as Map);
      expect(
        outcomes,
        contains(expected["outcome"]),
        reason: entry["name"] as String,
      );
      expect(expected.keys.toSet(), <String>{
        "outcome",
        "action",
        "cleanupAuthorized",
        "reason",
      });
    }
  });

  test("untrusted or ambiguous recovery never authorizes cleanup", () async {
    final fixture = await _readJson(fixturePath);
    const closedCases = <String>{
      "live owner recovery rejection",
      "torn journal write",
      "short journal write",
      "disk full before journal replacement",
      "directory flush failure",
      "corrupt journal",
      "unknown journal version",
      "injected prepared sibling name",
      "owner generation mismatch",
      "ambiguous target and backup state",
    };
    for (final entry in _mapList(fixture, "recoveryCases")) {
      if (!closedCases.contains(entry["name"])) {
        continue;
      }
      final expected = Map<String, dynamic>.from(entry["expected"] as Map);
      expect(expected["outcome"], "manualActionRequired");
      expect(expected["cleanupAuthorized"], isFalse);
      expect(expected["action"], "none");
    }
  });

  test("journal crash fixtures are generated byte-for-byte", () async {
    final root = await Directory.systemTemp.createTemp("helper_journal_");
    try {
      final result = await _runGenerator(
        generatorPath,
        <String>["--output", root.path],
      );
      expect(result.exitCode, 0, reason: _processReason(result));
      expect(
        _canonicalTextBytes(
          await File(path.join(root.path, "journal-transitions.json"))
              .readAsBytes(),
        ),
        _canonicalTextBytes(await File(fixturePath).readAsBytes()),
      );
    } finally {
      await root.delete(recursive: true);
    }
  });

  test("common recovery implementation remains non-destructive", () {
    final source = File(
      "native_runtime/cpp/install_helper_contract.cc",
    ).readAsStringSync();
    for (final forbidden in <String>[
      "<filesystem>",
      "<fstream>",
      "std::filesystem",
      "std::remove(",
      "std::rename(",
      "CreateFile",
      "DeleteFile",
      "ShellExecute",
      " open(",
      " unlink(",
      " rename(",
    ]) {
      expect(source, isNot(contains(forbidden)), reason: forbidden);
    }
  });
}

Future<Map<String, dynamic>> _readJson(String filePath) async {
  return Map<String, dynamic>.from(
    jsonDecode(await File(filePath).readAsString()) as Map,
  );
}

List<Map<String, dynamic>> _mapList(
  Map<String, dynamic> source,
  String key,
) {
  return (source[key] as List)
      .map((entry) => Map<String, dynamic>.from(entry as Map))
      .toList(growable: false);
}

Future<ProcessResult> _runGenerator(
  String generatorPath,
  List<String> arguments,
) {
  final executableName = Platform.isWindows ? "dart.exe" : "dart";
  final flutterRoot = Platform.environment["FLUTTER_ROOT"];
  var executable = executableName;
  if (flutterRoot != null) {
    executable = path.join(
      flutterRoot,
      "bin",
      "cache",
      "dart-sdk",
      "bin",
      executableName,
    );
  } else {
    for (final directory in (Platform.environment["PATH"] ?? "")
        .split(Platform.isWindows ? ";" : ":")) {
      final wrapper = File(path.join(directory, executableName));
      if (!wrapper.existsSync()) {
        continue;
      }
      final candidate = path.join(
        Directory(directory).parent.path,
        "bin",
        "cache",
        "dart-sdk",
        "bin",
        executableName,
      );
      executable = File(candidate).existsSync() ? candidate : wrapper.path;
      break;
    }
  }
  return Process.run(
    executable,
    <String>[generatorPath, ...arguments],
    environment: <String, String>{
      ...Platform.environment,
      "DART_TOOL_DISABLE_ANALYTICS": "1",
    },
  );
}

String _processReason(ProcessResult result) {
  return "exit=${result.exitCode}\nstdout=${result.stdout}\nstderr=${result.stderr}";
}

List<int> _canonicalTextBytes(List<int> bytes) =>
    utf8.encode(utf8.decode(bytes).replaceAll("\r\n", "\n"));
