<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>true</UseAppHost>
    <RollForward>Major</RollForward>
    <NuGetAudit>false</NuGetAudit>
    <DesktopUpdaterNativeVersion Condition="'$(DesktopUpdaterNativeVersion)' == ''">3.0.0</DesktopUpdaterNativeVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DesktopUpdater.Native" Version="$(DesktopUpdaterNativeVersion)" />
  </ItemGroup>
</Project>
